# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import federated_pb2 as federated__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in federated_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/federated.FederatedService/RegisterClient',
                request_serializer=federated__pb2.RegisterRequest.SerializeToString,
                response_deserializer=federated__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.SendLoRA = channel.unary_unary(
                '/federated.FederatedService/SendLoRA',
                request_serializer=federated__pb2.EncryptedLoRARequest.SerializeToString,
                response_deserializer=federated__pb2.LoRAResponse.FromString,
                _registered_method=True)
        self.GetGlobal = channel.unary_unary(
                '/federated.FederatedService/GetGlobal',
                request_serializer=federated__pb2.GlobalRequest.SerializeToString,
                response_deserializer=federated__pb2.EncryptedGlobalResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/federated.FederatedService/Heartbeat',
                request_serializer=federated__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=federated__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class FederatedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLoRA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """===============================
        NEW HEARTBEAT RPC
        ===============================
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=federated__pb2.RegisterRequest.FromString,
                    response_serializer=federated__pb2.RegisterResponse.SerializeToString,
            ),
            'SendLoRA': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLoRA,
                    request_deserializer=federated__pb2.EncryptedLoRARequest.FromString,
                    response_serializer=federated__pb2.LoRAResponse.SerializeToString,
            ),
            'GetGlobal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobal,
                    request_deserializer=federated__pb2.GlobalRequest.FromString,
                    response_serializer=federated__pb2.EncryptedGlobalResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=federated__pb2.HeartbeatRequest.FromString,
                    response_serializer=federated__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.FederatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated.FederatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/RegisterClient',
            federated__pb2.RegisterRequest.SerializeToString,
            federated__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLoRA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/SendLoRA',
            federated__pb2.EncryptedLoRARequest.SerializeToString,
            federated__pb2.LoRAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/GetGlobal',
            federated__pb2.GlobalRequest.SerializeToString,
            federated__pb2.EncryptedGlobalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/Heartbeat',
            federated__pb2.HeartbeatRequest.SerializeToString,
            federated__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
