# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\"A\n\x0fRegisterRequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\x12\x19\n\x11\x63lient_public_key\x18\x02 \x01(\x0c\">\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x11server_public_key\x18\x02 \x01(\x0c\"\x9e\x01\n\x14\x45ncryptedLoRARequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\x12\x15\n\rencrypted_key\x18\x02 \x01(\x0c\x12\x12\n\niv_weights\x18\x03 \x01(\x0c\x12\x11\n\tiv_config\x18\x04 \x01(\x0c\x12\x19\n\x11\x65ncrypted_weights\x18\x05 \x01(\x0c\x12\x18\n\x10\x65ncrypted_config\x18\x06 \x01(\x0c\"\x1f\n\x0cLoRAResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\rGlobalRequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\"\x9d\x01\n\x17\x45ncryptedGlobalResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\rencrypted_key\x18\x02 \x01(\x0c\x12\x12\n\niv_weights\x18\x03 \x01(\x0c\x12\x11\n\tiv_config\x18\x04 \x01(\x0c\x12\x19\n\x11\x65ncrypted_weights\x18\x05 \x01(\x0c\x12\x18\n\x10\x65ncrypted_config\x18\x06 \x01(\x0c\"\'\n\x10HeartbeatRequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\"$\n\x11HeartbeatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb6\x02\n\x10\x46\x65\x64\x65ratedService\x12I\n\x0eRegisterClient\x12\x1a.federated.RegisterRequest\x1a\x1b.federated.RegisterResponse\x12\x44\n\x08SendLoRA\x12\x1f.federated.EncryptedLoRARequest\x1a\x17.federated.LoRAResponse\x12I\n\tGetGlobal\x12\x18.federated.GlobalRequest\x1a\".federated.EncryptedGlobalResponse\x12\x46\n\tHeartbeat\x12\x1b.federated.HeartbeatRequest\x1a\x1c.federated.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=30
  _globals['_REGISTERREQUEST']._serialized_end=95
  _globals['_REGISTERRESPONSE']._serialized_start=97
  _globals['_REGISTERRESPONSE']._serialized_end=159
  _globals['_ENCRYPTEDLORAREQUEST']._serialized_start=162
  _globals['_ENCRYPTEDLORAREQUEST']._serialized_end=320
  _globals['_LORARESPONSE']._serialized_start=322
  _globals['_LORARESPONSE']._serialized_end=353
  _globals['_GLOBALREQUEST']._serialized_start=355
  _globals['_GLOBALREQUEST']._serialized_end=391
  _globals['_ENCRYPTEDGLOBALRESPONSE']._serialized_start=394
  _globals['_ENCRYPTEDGLOBALRESPONSE']._serialized_end=551
  _globals['_HEARTBEATREQUEST']._serialized_start=553
  _globals['_HEARTBEATREQUEST']._serialized_end=592
  _globals['_HEARTBEATRESPONSE']._serialized_start=594
  _globals['_HEARTBEATRESPONSE']._serialized_end=630
  _globals['_FEDERATEDSERVICE']._serialized_start=633
  _globals['_FEDERATEDSERVICE']._serialized_end=943
# @@protoc_insertion_point(module_scope)
